### ISSUE TITLE
Introducción

### ISSUE THREAD

**Issue by XaloFermac** [CIFP-Jose-luis-Garci/Iman#1]
- [x] PORTADA
- [x] ÍNDICE
- [x] INTRODUCCIÓN
   - [x] Concepto del juego:
   - [x] Características Principales

**Comment by IvanQuesadaGarcia** [comment]
**Concepto:** Nuestro juego se basa en el uso de imanes con diferentes herramientas para resolver puzles y avanzar por un entorno desconocido y conocer la historia que lo rodea.

**Comment by IvanQuesadaGarcia** [comment]
**Características principales:** 
-Mecánica de los imanes
-Exploración del mapa
-Resolución de puzles
-Movimiento cómodo y fluido
-Sensación de avance y mejora
