### ISSUE TITLE
Música y efectos

### ISSUE THREAD

**Issue by IvanQuesadaGarcia** [CIFP-Jose-luis-Garci/Iman#10]
- [x] ESTILO SONORO
- [x] DIFERENTES TEMAS MUSICALES
- [x] EFECTOS

**Comment by XaloFermac** [comment]
El juego contará con un estilo sonoro generalmente desenfadado, aunque depende del momento tenga presentes temas mucho más dinámicos y que influyan presión o incomodidad en el jugador.

La filosofía detrás de la banda sonora es el uso de leitmotifs. Los efectos sonoros se caracterizarán por sonar “blandos”, similares a lo que escucharíamos en stardew valley.

Las principales influencias para la creación de la banda sonora serán Undertale, Pikuniku y Pokémon Diamante, Perla y Platino.

**Comment by XaloFermac** [comment]
Aquío una demo de un tema de fondo y unos cuantos jingles/fanfares


[jingles obtenión objeto.zip](https://github.com/CIFP-Jose-luis-Garci/Iman/files/7529441/jingles.obtenion.objeto.zip)
[instrumental v1,1 VERY EARLY DEMO.zip](https://github.com/CIFP-Jose-luis-Garci/Iman/files/7529443/instrumental.v1.1.VERY.EARLY.DEMO.zip)
