### ISSUE TITLE
Referentes

### ISSUE THREAD

**Issue by IvanQuesadaGarcia** [CIFP-Jose-luis-Garci/Iman#11]

**Comment by IvanQuesadaGarcia** [comment]
**REFERENTES**

La referencia principal viene del videojuego “Portal”, un juego de puzzles utilizando la mecánica de portales de teletransporte para llegar a sitios inaccesibles, mover objetos, desviar láseres… En definitiva, un juego de puzzles con una mecánica poco explorada en el mundillo y muy bien pulida.

También nos inspiramos en “Hollow Knight”, sobre todo en el control del personaje y el mapeado, ya que en este Metroidvania todo se siente muy fluido y bien calculado, sobre todo una vez practicas un poco con tus habilidades, y las zonas y el mapa están perfectamente preparadas para que el jugador se pierda lo justo, sin quedarse completamente enganchado. Por otro lado, el estilo visual de este juego es muy limpio, detallado y a la vez simple, haciéndolo muy atractivo a la vista.

Los escenarios a su vez están inspirados en “Jetpack Joyride” y “de Blob 2”, ya que estos están ambientados en entornos similares a fábricas, laboratorios e instalaciones en el subsuelo.

Para las peleas contra jefes y enemigos nos basamos en Super Meat Boy, ya que en este juego realmente no peleas contra nadie, sino que descubres los patrones de ataque y resuelves un pequeño puzzle para derrotar a los enemigos.

Por último, tanto Super Mario Maker como Geometry Dash nos inspiraron a introducir un creador de niveles con todos los elementos del juego para que la comunidad pueda hacer sus propios niveles de puzzles, desarrollar su creatividad y compartirlos con el mundo.

**Comment by vcalzadaga** [comment]
Muy bien
