### ISSUE TITLE
Diagrama de Gantt

### ISSUE THREAD

**Issue by IvanQuesadaGarcia** [CIFP-Jose-luis-Garci/Iman#16]

**Comment by XaloFermac** [comment]
| Fase del proyecto | Tareas | Desc. tarea | Antecesor | Duración |
| ------------- | ------------- | ------------- | ------------- | :-------------: |
| Preproducción | -  | -  | -  | 12 |
| -  | Idea | Preparar la idea del juego | -  | 2 |
| -  | Concept Art | Dibujar los bocetos del juego  | Idea  | 5 |
| -  | GDD | Realizar el GDD con todos los datos | Idea  | 3 |
| -  |Diagrama Gantt | Preparar y distribuir las tareas en el tiempo  | GDD  | 2 |
| Producción | - | -  | Preproducción  | 37  |
| -  | Sprites | Hacer los sprites de personajes y plataformas  | GDD  | 14 |
| -  | Escenarios | Dibujar los escenarios de fondo  | GDD  | 4 |
| -  | HUD | Diseñar la HUD de menús e in-game  | GDD  | 2 |
| -  | Programar movimiento  | Programar los movimientos de personajes y plataformas  | Sprites | 7 |
| -  | Programar escenarios | Programar los escenarios con todos los objetos necesarios, interactividad y conexión entre habitaciones | Escenarios  | 8 |
| -  | Programar HUD  | Programar menús y HUD in-game funcional | HUD  | 2 |
| Postproducción | - | -  | -  | Contenido de la celda  |
| -  | Música y efectos  | Incorporar la música y los SFX del juego | Producción  | 10 |
| -  | Arreglos  | Arreglar fallos encontrados tras la alfa | Versión alfa  | 11 |
| Total | - | - | - | 70 |

**Comment by XaloFermac** [comment]
[iman gantt.zip](https://github.com/CIFP-Jose-luis-Garci/Iman/files/7706513/iman.gantt.zip)
