### ISSUE TITLE
PEGI, carátula y formulario de testeo

### ISSUE THREAD

**Issue by IvanQuesadaGarcia** [CIFP-Jose-luis-Garci/Iman#18]
Indicar la clasificación PEGI con los descriptores necesarios.

**Comment by IvanQuesadaGarcia** [comment]
PEGI 7 (contiene violencia)

El juego tiene un aspecto estilizado de dibujo animado, que contiene violencia muy leve entre personajes fantásticos no humanos. No hay sangre y los golpes no son contundentes como para considerarse violencia explícita, por lo que es apto para los niños a partir de 7 años.
![image](https://user-images.githubusercontent.com/77450492/151792965-130265b1-43f9-4389-ae39-f7ee89b33c20.png) ![image](https://user-images.githubusercontent.com/77450492/151792979-08494229-2044-4858-ab88-68f35e1c9ff5.png)

_Breve resumen del juego_

Conviértete en I·MAN y descubre un gran mundo subterráneo abandonado. Pelea, resuelve puzzles y explora para lograr salir a la superficie.

 _Problemas específicos del contenido_

Al atacar a las criaturas robóticas, estas dan un salto hacia atrás como reacción y al golpearlas varias veces, se desactivan y se rompen para desaparecer al rato. Hay batallas contra bosses que pueden asustar a niños pequeños.

**Comment by IvanQuesadaGarcia** [comment]
Formulario

https://forms.gle/LNvkZmBdvXi1kXcP8

[Formulario de testeo de I·MAN.pdf](https://github.com/CIFP-Jose-luis-Garci/Iman/files/7997459/Formulario.de.testeo.de.I.MAN.pdf)

**Comment by XaloFermac** [comment]
![IMAN COVER Switch](https://user-images.githubusercontent.com/77780401/152442615-719af4cc-271d-4e38-9c57-b02c90c951f3.png)
![BACK COVER](https://user-images.githubusercontent.com/77780401/152442825-27559b67-5a04-4f8b-af04-6b92ab0cf60c.png)
![IMAN COVER DIGITAL](https://user-images.githubusercontent.com/77780401/152442934-0a8840b7-0ca5-4795-b3dd-fbb78639226d.png)
