### ISSUE TITLE
Género y plataforma

### ISSUE THREAD

**Issue by XaloFermac** [CIFP-Jose-luis-Garci/Iman#2]
- [x] GÉNERO
- [x] PLATAFORMA
   - [x] Justificar por qué esa plataforma
   - [x] Tomar referencia de AEVI

**Comment by IvanQuesadaGarcia** [comment]
**Género:** Metroidvania, plataformas y puzles.

**Comment by IvanQuesadaGarcia** [comment]
**Plataforma:** PC y consolas, con controles tanto con teclado y ratón como con mando.
La plataforma PC es la opción más versátil en cuanto a controles y potencia, aunque no será necesario un equipo muy potente ya que el juego no tiene requisitos demasiado altos.
Debido a que el control está enfocado a mando, ya que resultará más cómodo, los jugadores de consola también podrán jugar sin ningún inconveniente.
Por otro lado, las consolas tienen un porcentaje más alto de jugadores que PC, por lo que es altamente probable que gran parte de los ingresos vengan proporcionados por consolas.
