### ISSUE TITLE
Personajes

### ISSUE THREAD

**Issue by IvanQuesadaGarcia** [CIFP-Jose-luis-Garci/Iman#4]
- [x] PERSONAJES JUGABLES
- [x] NPCS
- [x] ENEMIGOS

**Comment by IvanQuesadaGarcia** [comment]
**Personajes jugables:** Como personaje jugable solo estará I·MAN, el protagonista de la historia. Es un robot creado por el Estado que despierta en un lugar abandonado. Está equipado con una mochila bastante grande donde puede guardar las herramientas que va consiguiendo a lo largo de su camino y cambiar la polaridad de sus imanes. No es demasiado expresivo, pero genera ternura con sus animaciones, para que los jugadores se puedan encariñar sin tener que crear una relación de empatía con el personaje.

**NPCs:** M.A.G.N.O. (Magnetic Artificial Guard Neural Overwatch) // Magnolia es una IA al mando de todo el lugar en el que está atrapado I·MAN. A lo largo de la historia, Magnolia es la antagonista, ya que trata de pararle los pies al jugador, pero como se descubrirá al final, su objetivo es hacer el bien ya que I·MAN es malvado. 
Esta IA tiene una gran personalidad, fue programada para ser una gran líder y al final de la historia logra crear una sensación de empatía en el jugador.

**Enemigos:** Existen varios tipos de enemigos (diferentes tamaños y formas), que serán robots guardianes encargados de bloquear al jugador. Cada uno tendrá sus propias formas de ser derrotados mediante mini-puzzles con las herramientas. 

El enemigo más básico será un robot bípedo con un cuerpo pequeño y sin brazos y una cabeza semicúbica con una lente luminosa. Este enemigo es aproximadamente del tamaño de I·MAN y su forma de actuar es caminar en un área, ignorando al jugador, pero dañándolo con el contacto.

El siguiente enemigo es parecido al anterior, pero tiene la cabeza reforzada con una especie de máscara, ya que al ver a I·MAN comienza a cargar hacia él.

Otro enemigo es un androide de aspecto similar a I·MAN, aunque con los colores de los guardianes de la prisión. Este enemigo mantiene su posición y comienza a disparar en línea recta al ver al jugador, con un intervalo suficiente para que este pueda evitarlos.

Uno de los bosses es un robot grande, que dobla o triplica el tamaño de I·MAN, con piernas pequeñas pero un torso y brazos muy grandes, que tratará de aplastar a I·MAN con fuertes golpes hacia el suelo y puñetazos. Al ser uno de los bosses más básicos, no tiene mucha complicación derrotarlo. Este enemigo tiene un punto débil en la parte de la espalda, y el jugador debe utilizar el Yo-Ión y esperar a que el techo se vuelva magnético para poder subir sobre este enemigo y golpear su punto débil.

Un boss más avanzado es un enemigo monumental, que ocupa casi toda la pantalla, pero está en el fondo, y lo que puede interactuar con I·MAN son sus manos, que golpean las plataformas del escenario haciéndolas caer momentáneamente. El jugador debe evitar estos agujeros usando el Yo-Ión, el jetpack o las magnetobotas y sobrevivir hasta que aparezca una caja magnética con pinchos, que deberá mover con la MMMagnum justo debajo de las manos del boss para herirle cuando este golpee.

**Comment by vcalzadaga** [comment]
Esta parte está muy poco desarrollada. En este punto de la GDD habría que hablar de cada tipo de enemigo y sus características específicas

Se puede hablar de sus habilidades, características físicas, movimientos...
