### ISSUE TITLE
Estilo visual

### ISSUE THREAD

**Issue by IvanQuesadaGarcia** [CIFP-Jose-luis-Garci/Iman#5]
- [x] CONCEPT ART
   - [x] DISEÑO DE PERSONAJES
   - [x] DISEÑO DE ESCENARIOS
   - [x] OBJETOS, ARMAS, POWER UPS, COLECCIONABLES...
   - [x] OTROS

**Comment by danibo3** [comment]
@XaloFermac la vagoneta es una vagoneta normal, o también va imantada y se le puede cambiar la polaridad???

**Comment by IvanQuesadaGarcia** [comment]
I·MAN
![I·MAN_Concept](https://user-images.githubusercontent.com/77450492/141076371-835decfe-ef32-44b5-8ba9-1a8c7a9ea2e7.png)

**Comment by IvanQuesadaGarcia** [comment]
Props varios
![Props_Concept](https://user-images.githubusercontent.com/77450492/141160071-d65cd799-9b32-4c9f-949c-76ad68aed180.png)

**Comment by IvanQuesadaGarcia** [comment]
Escenario conceptual
![Concept_Escenario](https://user-images.githubusercontent.com/77450492/141176028-4ad5b5e6-b703-437f-80f3-c9ebbdd7f608.png)

**Comment by danibo3** [comment]
Herramientas

![ITEMS](https://user-images.githubusercontent.com/77780183/141259749-da003bd2-ab4f-4787-98c4-cc4a50f676f6.png)

**Comment by danibo3** [comment]
Magno

![Magno](https://user-images.githubusercontent.com/77780183/141497103-70ab5ea1-ff0b-433d-8924-e1b31a0a87ec.png)

**Comment by danibo3** [comment]
Enemigos nº1 y nº2


![Enemigos](https://user-images.githubusercontent.com/77780183/141585691-61aedfe6-29b9-4d32-8bb4-13f5e28a24bb.png)
