### ISSUE TITLE
Interfaz

### ISSUE THREAD

**Issue by IvanQuesadaGarcia** [CIFP-Jose-luis-Garci/Iman#6]
- [x] MAPA DE NAVEGACIÓN
- [x] MENÚS
- [x] HUD

**Comment by IvanQuesadaGarcia** [comment]
**Mapa de navegación**
![image](https://user-images.githubusercontent.com/77450492/141266784-d6622eab-dae6-48f9-8394-51dbfb938f61.png)
Desde el menú principal el jugador puede ir a la pantalla de archivo, en la que seleccione la partida que quiere jugar de todos sus archivos de guardado, y al seleccionarla ir al propio juego.
También puede ir al menú de opciones, que lleva a una sola pantalla en la que el jugador puede configurar el juego seleccionando el apartado (Juego, Audio, Pantalla, Controles).
Otra opción es ir a la pantalla de comunidad, donde se puede elegir si crear tus propios niveles y ver los que ya están creados o buscar uno creado por otro jugador y probarlo.
Finalmente, hay un botón para salir del juego.

Desde cualquier pantalla de juego se puede abrir un menú de pausa que permite reanudar la partida, ir al menú de opciones o volver al menú principal.
Por último, hay una pantalla que también pausa el juego para que puedas ver el mapa conforme lo vas descubriendo.

**Comment by IvanQuesadaGarcia** [comment]
**HUD**
![ingame HUD](https://user-images.githubusercontent.com/77450492/141275031-9576327f-31da-4c3e-8e82-37443e685c91.png)

![ingame HUD Timer](https://user-images.githubusercontent.com/77450492/141275078-e1b53610-14d1-4a13-9585-e1282a031c19.png)

**Comment by XaloFermac** [comment]
![IMAN main menu](https://user-images.githubusercontent.com/77780401/141534761-a2545c1a-c8dd-48b8-9c7a-4dfd827c6304.png)
