### ISSUE TITLE
Dinámicas y mecánicas

### ISSUE THREAD

**Issue by IvanQuesadaGarcia** [CIFP-Jose-luis-Garci/Iman#7]
- [x] Dinámicas
- [x] Mecánicas

**Comment by IvanQuesadaGarcia** [comment]
**Dinámicas:** 
-Recompensa: al obtener herramientas como power ups el jugador se sentirá alegre, ya que sus posibilidades se han expandido.
-Progreso: el jugador siente que avanza cuando encuentra una nueva zona que explorar, al avanzar entre los puzzles, al entender un poco de la historia...
-Expresión: capacidad de compartir con la comunidad tus propios niveles gracias al creador de niveles.
-Reflexión: el jugador irá entendiendo que él no es el bueno de la historia, y su punto de vista sobre los personajes cambiará.

**Comment by IvanQuesadaGarcia** [comment]
**Mecánicas:**
-Imanes: con el uso de diferentes objetos, el jugador podrá usar el magnetismo como principal herramienta, variando el uso en cada útil, por ejemplo, el Yo-Ión tiene un extremo imantado sujeto por una cuerda, permitiendo al jugador utilizarlo como una liana, o las botas magnéticas, que permitirán agarrarse a ciertas superficies o evitar zonas peligrosas, como pinchos metálicos.
-Puzzles: los jugadores se encontrarán frente a una gran variedad de puzles para poder avanzar, que tendrán que resolver utilizando las diferentes herramientas magnéticas en diferentes ámbitos. Por ejemplo, quizás un puzzle sea una zona de plataformas que tendrán que superar combinando objetos, o puede que el jugador necesite accionar un mecanismo al que no llega, pero usando la “mmmagnum” puede empujar algunas cajas para alcanzar el interruptor...
-Niveles: aunque no estarán definidos como tal, sino más bien como “salas” dentro del mapa, dando la impresión de mundo “abierto”, ya que al ser metroidvania, el jugador debe tener cierta libertad para avanzar, pero en nuestro caso los puzzles están bien definidos.
-Salto: con ayuda de las herramientas imantadas, los jugadores tendrán que superar zonas de plataformas saltando.
-Exploración: El mapa no te indicará cuál es tu objetivo actual, sino que el jugador debe explorar el mundo, buscar nuevas zonas a las que llegar con sus herramientas actuales, perderse de vez en cuando hasta encontrar un nuevo secreto...
-Enfrentamientos: no serán enfrentamientos exactamente, sino mini-puzzles con más acción. En el caso de los bosses serán puzzles más complejos. Un ejemplo es un enemigo básico que al ver al jugador cargará hacia él para herirle, pero este podrá saltar para esquivarlo y golpearlo con el Yo-Ión, un método sencillo para un enemigo primerizo para que el jugador aprenda.
-Diálogos: Sirven para explicar la historia. Se podrán ver estos diálogos mediante altavoces distribuidos por el entorno que usará Magnolia para comunicarse con el jugador, al hablar frente a frente con la misma, y en pequeños textos ocultos por el mapa que contarán pequeños fragmentos de historia.

**Comment by vcalzadaga** [comment]
Las mecánicas están poco desarrolladas. Podéis hablar un poco más de ellas, poner algún ejemplo, relacionarlo con las dinámicas... La explicación es demasiado esquemática
