### ISSUE TITLE
Movimientos y físicas

### ISSUE THREAD

**Issue by IvanQuesadaGarcia** [CIFP-Jose-luis-Garci/Iman#8]
- [x] CONTROLES
- [x] INTERACCIÓN

**Comment by vcalzadaga** [comment]
No hay ningún archivo asociado por lo que asumo que la tarea no está completada. La vuelvo a abrir

**Comment by IvanQuesadaGarcia** [comment]
**MOVIMIENTO Y FÍSICAS**

**Controles:**

(Esquema relatado en formato qwerty y layout de XBOX)

Movimiento con WASD o joystick izquierdo/cruceta

Salto con Espacio o A

cámara/mirar alrededor con flechas o con joystick derecho.

Inversión de polaridad con gatillo izquierdo

Menú con Start/esc

Mapa con Select/M

**Controles en menú:**

Pendiente de ver cómo se diseña la UI, la navegación va a consistir en:

A para aceptar
B para cancelar / volver atrás
Joystick izq/ cruceta para moverse arriba y abajo
RB y LB para ir navegando entre menús horizontales
Start para confirmar cambios



**Funcionamiento de artefactos**


Yo-ión tiene una angulación de 60º ascendente (posiblemente upgradeable hasta los 85º a posteriori conforme avance el juego, y en el tutorial empieza con 45º y acto seguido se mejora hasta los 60º) , de tal forma que es capaz de golpear enemigos y buscar posibles lugares donde engancharse. se va a controlar de tal forma:

gatillo derecho activa la animación/acción, golpeando a posibles enemigos y adhiriéndose a las superficies que se encuentre/con las que colisione

MMMAGNUM se activa también con el trigger derecho, cuando esto ocurra se ralentizará el tiempo, el movimiento de I·MAN quedará bloqueado y con el joystick de movimiento se tirará o empujará del elemento magnetizado solamente en el eje horizontal, ejerciendo el objeto una leve resistencia inicial al movimiento (si se usa la cruceta avanzará por pequeños sectores/porcentajes de un 10-20%, haciendo más precisa la acción pero menos dinámica). Una vez acabada la acción se suelta el gatillo y el tiempo vuelve a la normalidad, sin darle ningún tipo de salto extra a I·MAN.

Los bumpers servirán para rotar entre artefactos, sirviendo el bumper derecho [RB] para rotar entre los artefactos ofensivos (Yo-ión y MMMAGNUM) y el bumper izquierdo [LB] para rotar entre los artefactos de movilidad (Magnetobotas, Jetpack y Alas).

Cuando se obtengan las magnetobotas, el bumper simplemente actuará como un interruptor de encendido / apagado, pero en cuanto se consiga el siguiente artefacto (el jetpack) procederá a alternar entre herramientas de manera normal.

Los artefactos de movilidad se controlarán con el botón A (asignado al salto):

Las magnetobotas se adherirán y permitirán el salto, haciendo que se “ignore la gravedad natural” al permitir que se pueda caminar por un techo. La velocidad de movimiento se verá reducida en un 25-30%.


El jetpack actuará como el clásico doble salto. Posteriormente se podrá mejorar hasta incluso poseer 3 saltos extras, haciendo un total de 4 saltos *número de saltos extras pendiente de testeo*. Queda pendiente de ver si el número de saltos se reseteará  al tocar cualquier superficie o si el número de saltos extra se resetea una vez acabado cada nivel / sala.

Las alas permiten planear como lo harían unas elytra de Minecraft, si hay techo o suelos magnéticos serán sensibles a estos y tendrán una leve propiedad de atracción o repulsión que permitirán ascender o descender un poco en base a si está activada la atracción o la repulsión, pero en ningún caso podremos ascender una gran cantidad de altura usando solamente las alas, para ello lo más natural sería hacer uso del yo-ión como liana para impulsarse y ganar velocidad o cambiar rápidamente al jetpack y ascender usando un doble salto.

Cuando el jugador entre en una vagoneta se asignará a la ranura de artefactos de movilidad, y podrá realizar  saltos y cambiar la polaridad* de manera normal, así como hacer uso de los artefactos ofensivos. Sin embargo no se podrá hacer uso de los artefactos de movilidad. Para poder salir de la vagoneta se deberá pulsar el bumper derecho [LB] o la tecla que se tenga asignada a la rotación de artefactos de movilidad. 

* (hay que ver si interesa más que la vagoneta tenga un imán de cada polaridad o de la misma en cada uno de sus extremos o si la energía es imbuida por I·MAN y se deja elegir libremente al jugador que quiere hacer; pero creo que apostaré más por lo primero.)


**Atracción/ repulsión idle:**


cuando las herramientas estén sin activar, estas actuarán de la siguiente forma:

Yo-ión: no hará nada, puedes ir caminando libremente sin que generes ningún tipo de campo magnético

MMMAGNUM: funcionará de manera normal, por lo que si se desea avanzar sin ningún tipo de atracción se deberá cambiar al Yo-ión *Mecánica pendiente de revisión*. También es posible que el magnetismo se pueda desactivar manteniendo pulsado el botón X.

Magnetobotas: generarán campo magnético, por lo que si deseamos ir libremente sin activar campo magnético deberemos cambiar al jetpack o pulsar el botón X

Jetpack: no genera

Alas: generan un leve campo magnético

Vagoneta siempre estará generando campo magnético cuando el jugador esté montado o se haya montado.

**Elementos del mundo:**

Los elementos del mundo que sean magnéticos podrán estar presentes en estado de atracción (azul) o repulsión (rosa), sin que estos estados puedan ser alterados. Estos elementos pueden llegar a reaccionar entre sí, aunque no tendrán mucho poder de atracción o repulsión.



**Distancia de atracción / repulsión in-game:** 


Distancia en la que los objetos comienzan a hacer efectivo el campo magnético, por poner un ejemplo, la distancia que hay entre la parte más extrema del artefacto, la punta del imán de la MMMAGNUM, y el borde de una plataforma magnética.

Para poder explicarlo de forma fácil, tomaremos como unidad de referencia la altura del personaje I·MAN y la denominaremos UNIT. 

Yo-ión: el rango de atracción/ repulsión es de 1UNIT
MMMAGNUM: 3UNITS
Botas 1.5/2 UNITS
Jetpack: no tiene
Alas:1.5/2 UNITS
Vagoneta: 2UNITS
