### ISSUE TITLE
Diseño de niveles

### ISSUE THREAD

**Issue by IvanQuesadaGarcia** [CIFP-Jose-luis-Garci/Iman#9]
- [x] OBJETIVO DEL JUGADOR
- [x] FLUJO
- [x] NIVELES
- [x] DIFICULTAD
- [x] TUTORIAL

**Comment by IvanQuesadaGarcia** [comment]
**Objetivo del jugador:** el jugador comienza en lo más profundo de una prisión subterránea sin conocimiento de nada. Su objetivo en un principio será avanzar por un solo camino hasta obtener la primera herramienta, para poder recorrer más caminos, que dejarán de ser tan lineales. El jugador entenderá que tiene que usar su herramienta para avanzar, ya que aparecerán obstáculos en el camino que, poco a poco, se convertirán en puzzles con mayor o menor complejidad. Mientras explora, fragmentos de historia se irán revelando, haciendo entender al jugador que su objetivo es llegar a lo más alto para salir a la superficie.

**Comment by IvanQuesadaGarcia** [comment]
**Flujo:** para progresar, el jugador debe aprovechar al máximo todas las herramientas de las que dispone. El mundo tiene un factor de mundo abierto, en cuanto a que el jugador podrá explorarlo a su gusto siempre y cuando tenga las herramientas necesarias para hacerlo. La prisión se compone por salas y pasillos interconectados que tendrán distribución de plataformas o en algunos casos, puzzles, que podrán ser a contrarreloj o no.
Al ser golpeado por un enemigo, caer al vacío o en una trampa, I·MAN no morirá, pero regresará al comienzo de esa zona, obligando al jugador a moverse con agilidad para avanzar.
Las partidas se guardan al principio de cada sala, por lo que el jugador podrá salir cuando quiera del juego, sin perder progreso.
El juego se completa al completar la historia principal al salir a la superficie.

**Comment by IvanQuesadaGarcia** [comment]
**Dificultad:** la dificultad del juego no será tan elevada como para resultar frustrante, pero sí como para que el juego resulte un desafío. Al principio, los puzzles y los enemigos serán bastante sencillos, porque el jugador debe acostumbrarse a los controles y movimientos.
Conforme se avanza en el juego, la dificultad irá aumentando, aunque debido a que el juego no tiene un recorrido lineal, es posible que el jugador explore primero una zona más difícil que la siguiente que encuentre, ya que la dificultad se basará sobre todo en la cantidad de herramientas que tengas posibilidad de usar.
A su vez, la dificultad de los bosses se basará en esto también, aunque es posible que un jugador sienta más dificultad en un boss que otro jugador con el mismo, ya que cada uno tiene sus propios patrones y puzzles, por lo que dependen de la habilidad de los jugadores.
![Grafica de dificultad](https://user-images.githubusercontent.com/77450492/141343872-3a31c290-d6d9-4513-9a6c-9304765794f1.png)

**Comment by XaloFermac** [comment]
Aquí los primeros 1) niveles del tutorial, qeu sirven tambien para explicar como son los típicos niveles del inicio del juego


[niveles PDF.pdf](https://github.com/CIFP-Jose-luis-Garci/Iman/files/7530420/niveles.PDF.pdf)
